import crypto from 'node:crypto';
import {execFileSync} from 'node:child_process';
import {existsSync,readFileSync} from 'node:fs';
import path from 'node:path';
export const R=process.cwd(),Q='planning/prompt-quality',P=`${Q}/prompt-quality-execution-program.v1.json`,S=`${Q}/scopes/PROMPT-QUALITY-PROGRAM-ACTIVATION.scope.json`,I=`${Q}/impacts/0001-PROMPT-QUALITY-PROGRAM-ACTIVATION.json`,L=`${Q}/lifecycle/PROMPT-QUALITY-PROGRAM-ACTIVATION.ledger.json`,D=`${Q}/diagnostics/prompt-quality-diagnostics.v1.json`,F=`${Q}/fixtures`,C=`${Q}/current-scope.json`,N='planning/NEXT_WORK.md',PLAN='planning/PROMPT_QUALITY_EXECUTION_PLAN.md',REPO='rezahh107/Prompt-Pipeline',PID='PROMPT-QUALITY-MIGRATION-EXECUTION-PROGRAM',AT='PROMPT-QUALITY-PROGRAM-ACTIVATION';
export const PS=`${Q}/schemas/prompt-quality-execution-program.v1.schema.json`,SS=`${Q}/schemas/prompt-pipeline-task-scope.v1.schema.json`,IS=`${Q}/schemas/prompt-pipeline-progress-impact.v1.schema.json`,LS=`${Q}/schemas/prompt-pipeline-lifecycle-ledger.v1.schema.json`;
export const fp=x=>path.join(R,x),txt=x=>readFileSync(fp(x),'utf8'),json=x=>JSON.parse(txt(x)),cp=structuredClone,uniq=x=>[...new Set(x)].sort(),eq=(a,b)=>JSON.stringify(a)===JSON.stringify(b);
export const canon=x=>Array.isArray(x)?x.map(canon):x&&typeof x==='object'?Object.fromEntries(Object.keys(x).sort().map(k=>[k,canon(x[k])])):x;
export const hash=x=>`sha256:${crypto.createHash('sha256').update(JSON.stringify(canon(x))).digest('hex')}`;
export const rehash=(x,k)=>{const y=cp(x);delete y[k];x[k]=hash(y);return x};
export const sh=a=>{try{return execFileSync('git',a,{cwd:R,encoding:'utf8',stdio:['ignore','pipe','pipe']}).trim()}catch{return''}};
let codes=new Set();export const setCodes=x=>{codes=new Set(x)};
export const d=(code,message='',source='repository')=>codes.size&&!codes.has(code)&&code!=='PQG_DIAGNOSTIC_UNREGISTERED'?{code:'PQG_DIAGNOSTIC_UNREGISTERED',message:`Unregistered ${code}`,source}:{code,message,source};
let ajv=null;const validators=new Map();export async function schema(sp,v,src){try{if(!ajv){const A=(await import('ajv/dist/2020.js')).default;ajv=new A({allErrors:true,strict:true,allowUnionTypes:true})}let f=validators.get(sp);if(!f){f=ajv.compile(json(sp));validators.set(sp,f)}return f(v)?[]:(f.errors||[]).map(e=>d('PQG_SCHEMA_INVALID',`${src}${e.instancePath||'/'} ${e.message}`,src))}catch(e){if(process.env.PQG_SKIP_SCHEMA_VALIDATION==='1'&&!process.env.CI)return[];return[d('PQG_SCHEMA_INVALID',`schema validator unavailable: ${e?.message||e}`,src)]}}
export function requiredOutputs(p,s){const z=[];for(const x of s.required_outputs||[])if(!existsSync(fp(x)))z.push(d('PQG_REQUIRED_OUTPUT_MISSING',x,x));for(const o of p.activation_obligations||[])for(const x of o.required_paths||[])if(!existsSync(fp(x)))z.push(d('PQG_REQUIRED_OUTPUT_MISSING',x,x));return z}
export function diagnosticRegistry(reg,docs){const z=[],seen=new Set();for(const x of reg.entries||[]){if(seen.has(x.code))z.push(d('PQG_DIAGNOSTIC_UNREGISTERED',x.code,D));seen.add(x.code)}for(const doc of docs)for(const f of doc.fixtures||[])for(const x of f.expected_diagnostics||[])if(!seen.has(x))z.push(d('PQG_DIAGNOSTIC_UNREGISTERED',x,f.fixture_id));return z}
const REQ=['validate:prompt-quality-program','validate:prompt-quality-scope','validate:prompt-quality-progress','validate:prompt-quality-lifecycle','test:prompt-quality-governance','validate:prompt-quality-governance'];
export function ciWiring(){const z=[],s=json('package.json').scripts||{};for(const x of REQ)if(!s[x])z.push(d('PQG_CI_WIRING_MISSING',x,'package.json'));if(!(s.ci||'').includes('pnpm validate:prompt-quality-governance'))z.push(d('PQG_CI_WIRING_MISSING','ci','package.json'));return z}
export function gitContext(s){const c={reconcile:false,actual:s.committed_paths,deleted:[],head:null,base:null,retroactive:false,errors:[]};try{if(process.env.GITHUB_EVENT_PATH&&existsSync(process.env.GITHUB_EVENT_PATH))c.base=JSON.parse(readFileSync(process.env.GITHUB_EVENT_PATH,'utf8'))?.pull_request?.base?.sha||null}catch{}const want=process.env.PQG_SKIP_REPOSITORY_RECONCILIATION!=='1'&&(process.env.GITHUB_EVENT_NAME==='pull_request'||process.env.PQG_RECONCILE==='1');if(!want)return c;if(sh(['rev-parse','--is-inside-work-tree'])!=='true'){c.errors.push(d('PQG_GIT_EVIDENCE_UNAVAILABLE','not a worktree',R));return c}if(!sh(['rev-parse','--verify','-q',`${s.base_sha}^{commit}`]))try{execFileSync('git',['fetch','--no-tags','--depth=1','origin',s.base_sha],{cwd:R,stdio:'ignore'})}catch{c.errors.push(d('PQG_GIT_EVIDENCE_UNAVAILABLE','base unavailable',R));return c}c.head=sh(['rev-parse','HEAD']);const e=process.env.TESTED_SHA||process.env.GITHUB_SHA;if(e&&e!==c.head)c.errors.push(d('PQG_LIFECYCLE_HEAD_STALE',`${c.head} != ${e}`,R));if((s.amendments||[]).some(a=>!sh(['rev-parse','--verify','-q',`${a.authorization_commit_sha}^{commit}`])))try{execFileSync('git',['fetch','--no-tags','--deepen=256','origin',c.head],{cwd:R,stdio:'ignore'})}catch{c.errors.push(d('PQG_GIT_EVIDENCE_UNAVAILABLE','amendment history unavailable',R))}const rows=sh(['diff','--no-renames','--name-status',s.base_sha,c.head]).split('\n').filter(Boolean).map(x=>x.split('\t'));c.actual=uniq(rows.map(x=>x.at(-1)));c.deleted=uniq(rows.filter(x=>x[0]==='D').map(x=>x[1]));c.reconcile=true;const commits=sh(['rev-list','--reverse',`${s.base_sha}..${c.head}`]).split('\n').filter(Boolean);for(const a of s.amendments||[]){const boundary=commits.indexOf(a.authorization_commit_sha);if(boundary<0){c.retroactive=true;continue}for(const x of a.added_paths||[]){const first=commits.findIndex(h=>sh(['diff-tree','--no-commit-id','--name-only','-r',h]).split('\n').includes(x));if(first>=0&&first<=boundary)c.retroactive=true}}return c}
