import {P,N,PLAN,REPO,PID,PS,txt,fp,uniq,eq,d,schema} from './core.mjs';
import {existsSync} from 'node:fs';
export const IDS=Array.from({length:15},(_,i)=>`PPQR-${String(i+1).padStart(3,'0')}`);
export const DEPS={'PPQR-001':[],'PPQR-002':['PPQR-001'],'PPQR-003':['PPQR-001'],'PPQR-004':['PPQR-003'],'PPQR-005':['PPQR-003','PPQR-004'],'PPQR-006':['PPQR-001','PPQR-003','PPQR-004','PPQR-005'],'PPQR-007':['PPQR-003','PPQR-004','PPQR-006'],'PPQR-008':['PPQR-006','PPQR-007'],'PPQR-009':['PPQR-006','PPQR-007','PPQR-008'],'PPQR-010':['PPQR-006','PPQR-007','PPQR-008','PPQR-009'],'PPQR-011':['PPQR-002','PPQR-006','PPQR-007','PPQR-008','PPQR-010'],'PPQR-012':['PPQR-011'],'PPQR-013':['PPQR-009','PPQR-010','PPQR-012'],'PPQR-014':['PPQR-012','PPQR-013'],'PPQR-015':['PPQR-014']};
export const taskMap=p=>new Map((p.tasks||[]).map(t=>[t.task_id,t]));
export function derived(t,m){if(t.authorization_state!=='authorized')return'policy_blocked';return(t.depends_on||[]).every(x=>m.get(x)?.completion_state==='complete')?'eligible':'dependency_blocked'}
function hasCycle(m){const seen=new Set(),stack=new Set();function walk(id){if(stack.has(id))return true;if(seen.has(id))return false;seen.add(id);stack.add(id);for(const x of m.get(id)?.depends_on||[])if(x!==id&&m.has(x)&&walk(x))return true;stack.delete(id);return false}return[...m.keys()].some(walk)}
export async function validateProgram(p,ctx={}){let z=await schema(PS,p,P);if(p.program_id!==PID||p.repository!==REPO)z.push(d('PQG_PROGRAM_IDENTITY_INVALID','identity',P));const ids=(p.tasks||[]).map(t=>t.task_id),m=taskMap(p);if(ids.length!==15)z.push(d('PQG_PROGRAM_TASK_COUNT_INVALID','count',P));if(new Set(ids).size!==ids.length)z.push(d('PQG_PROGRAM_DUPLICATE_TASK','duplicate',P));for(const id of IDS)if(!m.has(id))z.push(d('PQG_PROGRAM_MISSING_TASK',id,P));for(const id of ids)if(!IDS.includes(id))z.push(d('PQG_PROGRAM_EXTRA_TASK',id,P));for(const t of p.tasks||[]){const want=DEPS[t.task_id];if(want&&!eq(uniq(t.depends_on||[]),uniq(want)))z.push(d('PQG_DEPENDENCY_MUTATION',t.task_id,t.task_id));if((t.depends_on||[]).includes(t.task_id))z.push(d('PQG_DEPENDENCY_SELF',t.task_id,t.task_id));for(const x of t.depends_on||[])if(!m.has(x))z.push(d('PQG_DEPENDENCY_UNKNOWN',x,t.task_id));const e=derived(t,m);if(t.execution_state!==e)z.push(d('PQG_ELIGIBILITY_MISMATCH',t.task_id,t.task_id));if(t.authorization_state!=='authorized'&&t.execution_state==='eligible')z.push(d('PQG_AUTHORIZATION_ELIGIBILITY_INVALID',t.task_id,t.task_id));const incomplete=(t.depends_on||[]).some(x=>m.get(x)?.completion_state!=='complete');if(t.implementation_state==='implemented'&&(incomplete||e!=='eligible'))z.push(d('PQG_PREMATURE_IMPLEMENTED',t.task_id,t.task_id));if(t.completion_state==='complete'&&(t.implementation_state!=='implemented'||incomplete))z.push(d('PQG_PREMATURE_COMPLETE',t.task_id,t.task_id))}if(hasCycle(m))z.push(d('PQG_DEPENDENCY_CYCLE','cycle',P));if(ctx.programComplete&&(p.tasks||[]).some(t=>t.completion_state!=='complete'))z.push(d('PQG_PROGRAM_COMPLETE_WITH_INCOMPLETE_TASK','incomplete',P));const e=p.effects||{};if(e.quality_credit||e.migration_promotion_effect!=='none'||e.production_authority_effect!=='none'||e.release_readiness_claim||e.production_readiness_claim||e.legacy_retirement_effect!=='none'||e.substantive_task_implementation!=='none')z.push(d('PQG_QUALITY_CLAIM_UNSUPPORTED','activation effects',P));return z}
export function validateMemory(p){const m=txt(N).match(/<!-- prompt-quality-status:start -->\s*```json\s*([\s\S]*?)\s*```/);if(!m)return[d('PQG_MEMORY_DRIFT','block missing',N)];const x=JSON.parse(m[1]),tm=taskMap(p),eligible=(p.tasks||[]).filter(t=>derived(t,tm)==='eligible').map(t=>t.task_id),blocked=(p.tasks||[]).filter(t=>derived(t,tm)==='dependency_blocked').map(t=>t.task_id),z=[];if(x.active_program!==p.program_id||x.authoritative_activation_state!==p.authoritative_activation_state||x.current_immediately_executable_task!==eligible[0]||!eq(x.dependency_blocked_tasks,blocked))z.push(d('PQG_MEMORY_DRIFT','derived status mismatch',N));if(!existsSync(fp(PLAN)))z.push(d('PQG_REQUIRED_OUTPUT_MISSING',PLAN,PLAN));return z}
