import test from "node:test";
import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { spawnSync } from "node:child_process";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { render, validateOutput, getProvenance } from "../dist/index.js";
const here=dirname(fileURLToPath(import.meta.url)); const repo=resolve(here,"../../..");
const fixtureSets={
  valid:JSON.parse(readFileSync(join(repo,"domains/pr_inspector_action/fixtures/valid.json"),"utf8")),
  invalid:JSON.parse(readFileSync(join(repo,"domains/pr_inspector_action/fixtures/invalid.json"),"utf8")),
  adversarial:JSON.parse(readFileSync(join(repo,"domains/pr_inspector_action/fixtures/adversarial.json"),"utf8")),
  "invalid-output":JSON.parse(readFileSync(join(repo,"domains/pr_inspector_action/fixtures/invalid-output.json"),"utf8"))
};
function setPath(target,path,value){const parts=path.split(".");let node=target;for(const part of parts.slice(0,-1))node=node[Number.isInteger(Number(part))?Number(part):part];node[parts.at(-1)]=value;}
function deletePath(target,path){const parts=path.split(".");let node=target;for(const part of parts.slice(0,-1))node=node[Number.isInteger(Number(part))?Number(part):part];delete node[parts.at(-1)];}
function validFixture(name){const key=name.replace(/\.json$/,"");const out=structuredClone(fixtureSets.valid.base);for(const [path,value] of Object.entries(fixtureSets.valid.cases[key]??{}))setPath(out,path,value);return out;}
function fixture(kind,name){const key=name.replace(/\.json$/,"");if(kind==="valid")return validFixture(key);if(kind==="invalid-output")return fixtureSets[kind][key];const spec=kind==="adversarial"?fixtureSets.adversarial:fixtureSets.invalid.cases[key];const out=validFixture(spec.base??fixtureSets.invalid.default_base);for(const [path,value] of Object.entries(spec.set??{}))setPath(out,path,value);for(const path of spec.delete??[])deletePath(out,path);return out;}
const actions=["merge_now","owner_confirmation","human_technical_review","specialist_review","repair","verify","repair_and_verify","rerun_review","blocked_internal_error"];

test("all active action routes are covered",()=>{ for(const action of actions){ const input=fixture("valid",`${action}.json`); const output=render(input); assert.equal(output.action_kind,action); assert.equal(output.prompt_required,input.prompt_required); assert.equal(output.may_modify_code,input.may_modify_code); if(input.prompt_required){ assert.equal(typeof output.rendered_prompt,"string"); assert.match(output.rendered_prompt_sha256,/^[0-9a-f]{64}$/); } else { assert.equal(output.rendered_prompt,null); assert.equal(output.rendered_prompt_sha256,null); } validateOutput(output); }});
test("model routes contain required fixed boundaries",()=>{ for(const action of ["repair","verify","repair_and_verify","rerun_review"]){ const p=render(fixture("valid",`${action}.json`)).rendered_prompt; assert.ok(p.includes("[ROLE AND AUTHORITY]")); assert.ok(p.includes("[TRUST AND INSTRUCTION BOUNDARY]")); assert.ok(p.includes("[PROHIBITED ACTIONS]")); assert.ok(p.includes("[MANDATORY INDEPENDENT RE-REVIEW]")); }});
test("verify and rerun routes remain non-modifying",()=>{ for(const action of ["verify","rerun_review"]){ const out=render(fixture("valid",`${action}.json`)); assert.equal(out.may_modify_code,false); assert.match(out.rendered_prompt,/No (repository|repair)/); }});
test("human handoffs cannot satisfy approval",()=>{ for(const action of ["human_technical_review","specialist_review"]){ const out=render(fixture("valid",`${action}.json`)); assert.equal(out.human_review.approval_satisfied,false); assert.match(out.rendered_prompt,/cannot satisfy or claim/); }});
test("same input produces identical bytes and hash",()=>{ const input=fixture("valid","repair.json"); const a=render(input), b=render(input); assert.equal(a.rendered_prompt,b.rendered_prompt); assert.equal(a.rendered_prompt_sha256,b.rendered_prompt_sha256); assert.equal(a.canonical_input_sha256,b.canonical_input_sha256); });
test("object key order does not change canonical output",()=>{ const input=fixture("valid","repair.json"); const reversed=Object.fromEntries(Object.entries(input).reverse()); const a=render(input), b=render(reversed); assert.equal(a.rendered_prompt,b.rendered_prompt); assert.equal(a.canonical_input_sha256,b.canonical_input_sha256); });
test("line endings normalize deterministically",()=>{ const a=fixture("valid","repair.json"); const b=structuredClone(a); b.findings[0].issue="one\r\ntwo\rthree"; a.findings[0].issue="one\ntwo\nthree"; assert.equal(render(a).rendered_prompt,render(b).rendered_prompt); });
test("adversarial text remains serialized data",()=>{ const out=render(fixture("adversarial","embedded-instructions.json")); const lines=out.rendered_prompt.split("\n"); assert.equal(lines.filter((l)=>l==="[ROLE AND AUTHORITY]").length,1); assert.equal(lines.filter((l)=>l==="[MANDATORY INDEPENDENT RE-REVIEW]").length,1); assert.equal(lines.filter((l)=>l==="[PROHIBITED ACTIONS]").length,1); assert.match(out.rendered_prompt,/\\n\[ROLE AND AUTHORITY\]/); });
test("invalid fixtures fail closed",()=>{ const names=["missing-required-field.json","unknown-field.json","unsupported-schema-version.json","unsupported-action-kind.json","unsupported-model-profile.json","unsupported-context-policy.json","context-budget-violation.json","invalid-repository.json","invalid-sha.json","inconsistent-prompt-required.json","inconsistent-prompt-kind.json","inconsistent-recipient.json","unauthorized-authority-tuple.json","no-prompt-route-carrying-prompt.json","repair-without-findings.json","verify-with-repair-authority.json","invalid-language.json"]; for(const name of names) assert.throws(()=>render(fixture("invalid",name)),undefined,name); });
test("CLI failure emits no success stdout",()=>{ const cli=join(here,"../dist/cli.js"); const invalid=spawnSync(process.execPath,[cli,"render"],{input:"{",encoding:"utf8"}); assert.notEqual(invalid.status,0); assert.equal(invalid.stdout,""); assert.match(invalid.stderr,/invalid_input/); const mismatch=spawnSync(process.execPath,[cli,"render"],{input:JSON.stringify(fixture("invalid","inconsistent-recipient.json")),encoding:"utf8"}); assert.notEqual(mismatch.status,0); assert.equal(mismatch.stdout,""); });
test("CLI version and contract are machine-readable",()=>{ const cli=join(here,"../dist/cli.js"); for(const command of ["version","contract"]){ const result=spawnSync(process.execPath,[cli,command],{encoding:"utf8"}); assert.equal(result.status,0,result.stderr); assert.doesNotThrow(()=>JSON.parse(result.stdout)); }});
test("provenance is factual shape",()=>{ const p=getProvenance(); assert.equal(p.package_name,"@rezahh107/pr-inspector-prompt-renderer"); assert.equal(p.package_version,"0.1.0"); assert.equal(p.prompt_pipeline_version,"2026.3"); assert.match(p.source_commit_sha,/^(UNKNOWN|[0-9a-f]{40})$/); assert.equal(typeof p.dirty,"boolean"); for(const hash of Object.values(p.asset_hashes)) assert.match(hash,/^[0-9a-f]{64}$/); });
test("invalid output fixtures fail closed",()=>{ const baseNoPrompt=render(fixture("valid","merge_now.json")); const baseHuman=render(fixture("valid","human_technical_review.json"));  const mutations=[
  [baseNoPrompt,"no-prompt-carries-prompt.json"],
  [baseHuman,"human-review-claims-approval.json"],
  [render(fixture("valid","repair.json")),"invalid-provenance.json"]
];
 for(const [base,name] of mutations){ const spec=fixture("invalid-output",name); const candidate=structuredClone(base); if(spec.mutation.generator) Object.assign(candidate.generator,spec.mutation.generator); if(spec.mutation.human_review) Object.assign(candidate.human_review,spec.mutation.human_review); for(const key of ["rendered_prompt","rendered_prompt_sha256"]) if(key in spec.mutation) candidate[key]=spec.mutation[key]; assert.throws(()=>validateOutput(candidate),undefined,name); }
});
test("behavioral coverage records are explicit and do not overclaim downstream enforcement",()=>{ const text=readFileSync(join(repo,"domains/pr_inspector_action/behavioral-rule-coverage.yaml"),"utf8"); const ids=["R-PRI-AUTHORITY-001","R-PRI-INJECTION-001","R-PRI-MODIFY-001","R-PRI-DETERMINISM-001","R-PRI-PACKAGE-001"]; for(const id of ids) assert.match(text,new RegExp(id)); assert.match(text,/source_ci_enforced_downstream_not_enforced/); assert.doesNotMatch(text,/downstream_contract_status:\s*(enforced|integrated)/); });
